extract_feature_set = {'abs_energy': None,
 'absolute_sum_of_changes': None,
 'agg_autocorrelation': [{'f_agg': 'mean'},
  {'f_agg': 'median'},
  {'f_agg': 'var'}],
 'agg_linear_trend': [{'attr': 'rvalue', 'chunk_len': 5, 'f_agg': 'max'},
  {'attr': 'rvalue', 'chunk_len': 5, 'f_agg': 'min'},
  {'attr': 'rvalue', 'chunk_len': 5, 'f_agg': 'mean'},
  {'attr': 'rvalue', 'chunk_len': 5, 'f_agg': 'var'},
  {'attr': 'rvalue', 'chunk_len': 10, 'f_agg': 'max'},
  {'attr': 'rvalue', 'chunk_len': 10, 'f_agg': 'min'},
  {'attr': 'rvalue', 'chunk_len': 10, 'f_agg': 'mean'},
  {'attr': 'rvalue', 'chunk_len': 10, 'f_agg': 'var'},
  {'attr': 'rvalue', 'chunk_len': 50, 'f_agg': 'max'},
  {'attr': 'rvalue', 'chunk_len': 50, 'f_agg': 'min'},
  {'attr': 'rvalue', 'chunk_len': 50, 'f_agg': 'mean'},
  {'attr': 'rvalue', 'chunk_len': 50, 'f_agg': 'var'},
  {'attr': 'intercept', 'chunk_len': 5, 'f_agg': 'max'},
  {'attr': 'intercept', 'chunk_len': 5, 'f_agg': 'min'},
  {'attr': 'intercept', 'chunk_len': 5, 'f_agg': 'mean'},
  {'attr': 'intercept', 'chunk_len': 5, 'f_agg': 'var'},
  {'attr': 'intercept', 'chunk_len': 10, 'f_agg': 'max'},
  {'attr': 'intercept', 'chunk_len': 10, 'f_agg': 'min'},
  {'attr': 'intercept', 'chunk_len': 10, 'f_agg': 'mean'},
  {'attr': 'intercept', 'chunk_len': 10, 'f_agg': 'var'},
  {'attr': 'intercept', 'chunk_len': 50, 'f_agg': 'max'},
  {'attr': 'intercept', 'chunk_len': 50, 'f_agg': 'min'},
  {'attr': 'intercept', 'chunk_len': 50, 'f_agg': 'mean'},
  {'attr': 'intercept', 'chunk_len': 50, 'f_agg': 'var'},
  {'attr': 'slope', 'chunk_len': 5, 'f_agg': 'max'},
  {'attr': 'slope', 'chunk_len': 5, 'f_agg': 'min'},
  {'attr': 'slope', 'chunk_len': 5, 'f_agg': 'mean'},
  {'attr': 'slope', 'chunk_len': 5, 'f_agg': 'var'},
  {'attr': 'slope', 'chunk_len': 10, 'f_agg': 'max'},
  {'attr': 'slope', 'chunk_len': 10, 'f_agg': 'min'},
  {'attr': 'slope', 'chunk_len': 10, 'f_agg': 'mean'},
  {'attr': 'slope', 'chunk_len': 10, 'f_agg': 'var'},
  {'attr': 'slope', 'chunk_len': 50, 'f_agg': 'max'},
  {'attr': 'slope', 'chunk_len': 50, 'f_agg': 'min'},
  {'attr': 'slope', 'chunk_len': 50, 'f_agg': 'mean'},
  {'attr': 'slope', 'chunk_len': 50, 'f_agg': 'var'},
  {'attr': 'stderr', 'chunk_len': 5, 'f_agg': 'max'},
  {'attr': 'stderr', 'chunk_len': 5, 'f_agg': 'min'},
  {'attr': 'stderr', 'chunk_len': 5, 'f_agg': 'mean'},
  {'attr': 'stderr', 'chunk_len': 5, 'f_agg': 'var'},
  {'attr': 'stderr', 'chunk_len': 10, 'f_agg': 'max'},
  {'attr': 'stderr', 'chunk_len': 10, 'f_agg': 'min'},
  {'attr': 'stderr', 'chunk_len': 10, 'f_agg': 'mean'},
  {'attr': 'stderr', 'chunk_len': 10, 'f_agg': 'var'},
  {'attr': 'stderr', 'chunk_len': 50, 'f_agg': 'max'},
  {'attr': 'stderr', 'chunk_len': 50, 'f_agg': 'min'},
  {'attr': 'stderr', 'chunk_len': 50, 'f_agg': 'mean'},
  {'attr': 'stderr', 'chunk_len': 50, 'f_agg': 'var'}],
 'approximate_entropy': [{'m': 2, 'r': 0.1},
  {'m': 2, 'r': 0.3},
  {'m': 2, 'r': 0.5},
  {'m': 2, 'r': 0.7},
  {'m': 2, 'r': 0.9}],
 'ar_coefficient': [{'coeff': 0, 'k': 10},
  {'coeff': 1, 'k': 10},
  {'coeff': 2, 'k': 10},
  {'coeff': 3, 'k': 10},
  {'coeff': 4, 'k': 10}],
 'augmented_dickey_fuller': [{'attr': 'teststat'},
  {'attr': 'pvalue'},
  {'attr': 'usedlag'}],
 'autocorrelation': [{'lag': 0},
  {'lag': 1},
  {'lag': 2},
  {'lag': 3},
  {'lag': 4},
  {'lag': 5},
  {'lag': 6},
  {'lag': 7},
  {'lag': 8},
  {'lag': 9}],
 'binned_entropy': [{'max_bins': 10}],
 'c3': [{'lag': 1}, {'lag': 2}, {'lag': 3}],
 'change_quantiles': [{'f_agg': 'mean', 'isabs': False, 'qh': 0.2, 'ql': 0.0},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.2, 'ql': 0.0},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.2, 'ql': 0.0},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.2, 'ql': 0.0},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.4, 'ql': 0.0},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.4, 'ql': 0.0},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.4, 'ql': 0.0},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.4, 'ql': 0.0},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.6, 'ql': 0.0},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.6, 'ql': 0.0},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.6, 'ql': 0.0},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.6, 'ql': 0.0},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.8, 'ql': 0.0},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.8, 'ql': 0.0},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.8, 'ql': 0.0},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.0},
  {'f_agg': 'mean', 'isabs': False, 'qh': 1.0, 'ql': 0.0},
  {'f_agg': 'var', 'isabs': False, 'qh': 1.0, 'ql': 0.0},
  {'f_agg': 'mean', 'isabs': True, 'qh': 1.0, 'ql': 0.0},
  {'f_agg': 'var', 'isabs': True, 'qh': 1.0, 'ql': 0.0},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.2, 'ql': 0.2},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.2, 'ql': 0.2},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.2, 'ql': 0.2},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.2, 'ql': 0.2},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.4, 'ql': 0.2},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.4, 'ql': 0.2},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.4, 'ql': 0.2},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.4, 'ql': 0.2},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.6, 'ql': 0.2},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.6, 'ql': 0.2},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.6, 'ql': 0.2},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.6, 'ql': 0.2},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.8, 'ql': 0.2},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.8, 'ql': 0.2},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.8, 'ql': 0.2},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.2},
  {'f_agg': 'mean', 'isabs': False, 'qh': 1.0, 'ql': 0.2},
  {'f_agg': 'var', 'isabs': False, 'qh': 1.0, 'ql': 0.2},
  {'f_agg': 'mean', 'isabs': True, 'qh': 1.0, 'ql': 0.2},
  {'f_agg': 'var', 'isabs': True, 'qh': 1.0, 'ql': 0.2},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.2, 'ql': 0.4},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.2, 'ql': 0.4},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.2, 'ql': 0.4},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.2, 'ql': 0.4},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.4, 'ql': 0.4},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.4, 'ql': 0.4},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.4, 'ql': 0.4},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.4, 'ql': 0.4},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.6, 'ql': 0.4},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.6, 'ql': 0.4},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.6, 'ql': 0.4},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.6, 'ql': 0.4},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.8, 'ql': 0.4},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.8, 'ql': 0.4},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.8, 'ql': 0.4},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.4},
  {'f_agg': 'mean', 'isabs': False, 'qh': 1.0, 'ql': 0.4},
  {'f_agg': 'var', 'isabs': False, 'qh': 1.0, 'ql': 0.4},
  {'f_agg': 'mean', 'isabs': True, 'qh': 1.0, 'ql': 0.4},
  {'f_agg': 'var', 'isabs': True, 'qh': 1.0, 'ql': 0.4},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.2, 'ql': 0.6},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.2, 'ql': 0.6},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.2, 'ql': 0.6},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.2, 'ql': 0.6},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.4, 'ql': 0.6},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.4, 'ql': 0.6},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.4, 'ql': 0.6},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.4, 'ql': 0.6},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.6, 'ql': 0.6},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.6, 'ql': 0.6},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.6, 'ql': 0.6},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.6, 'ql': 0.6},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.8, 'ql': 0.6},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.8, 'ql': 0.6},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.8, 'ql': 0.6},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.6},
  {'f_agg': 'mean', 'isabs': False, 'qh': 1.0, 'ql': 0.6},
  {'f_agg': 'var', 'isabs': False, 'qh': 1.0, 'ql': 0.6},
  {'f_agg': 'mean', 'isabs': True, 'qh': 1.0, 'ql': 0.6},
  {'f_agg': 'var', 'isabs': True, 'qh': 1.0, 'ql': 0.6},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.2, 'ql': 0.8},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.2, 'ql': 0.8},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.2, 'ql': 0.8},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.2, 'ql': 0.8},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.4, 'ql': 0.8},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.4, 'ql': 0.8},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.4, 'ql': 0.8},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.4, 'ql': 0.8},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.6, 'ql': 0.8},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.6, 'ql': 0.8},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.6, 'ql': 0.8},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.6, 'ql': 0.8},
  {'f_agg': 'mean', 'isabs': False, 'qh': 0.8, 'ql': 0.8},
  {'f_agg': 'var', 'isabs': False, 'qh': 0.8, 'ql': 0.8},
  {'f_agg': 'mean', 'isabs': True, 'qh': 0.8, 'ql': 0.8},
  {'f_agg': 'var', 'isabs': True, 'qh': 0.8, 'ql': 0.8},
  {'f_agg': 'mean', 'isabs': False, 'qh': 1.0, 'ql': 0.8},
  {'f_agg': 'var', 'isabs': False, 'qh': 1.0, 'ql': 0.8},
  {'f_agg': 'mean', 'isabs': True, 'qh': 1.0, 'ql': 0.8},
  {'f_agg': 'var', 'isabs': True, 'qh': 1.0, 'ql': 0.8}],
 'count_above_mean': None,
 'count_below_mean': None,
 'cwt_coefficients': [{'coeff': 0, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 0, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 0, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 0, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 1, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 1, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 1, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 1, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 2, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 2, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 2, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 2, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 3, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 3, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 3, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 3, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 4, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 4, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 4, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 4, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 5, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 5, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 5, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 5, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 6, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 6, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 6, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 6, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 7, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 7, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 7, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 7, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 8, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 8, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 8, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 8, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 9, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 9, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 9, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 9, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 10, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 10, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 10, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 10, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 11, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 11, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 11, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 11, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 12, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 12, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 12, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 12, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 13, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 13, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 13, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 13, 'w': 20, 'widths': (2, 5, 10, 20)},
  {'coeff': 14, 'w': 2, 'widths': (2, 5, 10, 20)},
  {'coeff': 14, 'w': 5, 'widths': (2, 5, 10, 20)},
  {'coeff': 14, 'w': 10, 'widths': (2, 5, 10, 20)},
  {'coeff': 14, 'w': 20, 'widths': (2, 5, 10, 20)}],
 'fft_coefficient': [{'attr': 'real', 'coeff': 0},
  {'attr': 'real', 'coeff': 1},
  {'attr': 'real', 'coeff': 2},
  {'attr': 'real', 'coeff': 3},
  {'attr': 'real', 'coeff': 4},
  {'attr': 'real', 'coeff': 5},
  {'attr': 'real', 'coeff': 6},
  {'attr': 'real', 'coeff': 7},
  {'attr': 'real', 'coeff': 8},
  {'attr': 'real', 'coeff': 9},
  {'attr': 'real', 'coeff': 10},
  {'attr': 'real', 'coeff': 11},
  {'attr': 'real', 'coeff': 12},
  {'attr': 'real', 'coeff': 13},
  {'attr': 'real', 'coeff': 14},
  {'attr': 'real', 'coeff': 15},
  {'attr': 'real', 'coeff': 16},
  {'attr': 'real', 'coeff': 17},
  {'attr': 'real', 'coeff': 18},
  {'attr': 'real', 'coeff': 19},
  {'attr': 'real', 'coeff': 20},
  {'attr': 'real', 'coeff': 21},
  {'attr': 'real', 'coeff': 22},
  {'attr': 'real', 'coeff': 23},
  {'attr': 'real', 'coeff': 24},
  {'attr': 'real', 'coeff': 25},
  {'attr': 'real', 'coeff': 26},
  {'attr': 'real', 'coeff': 27},
  {'attr': 'real', 'coeff': 28},
  {'attr': 'real', 'coeff': 29},
  {'attr': 'real', 'coeff': 30},
  {'attr': 'real', 'coeff': 31},
  {'attr': 'real', 'coeff': 32},
  {'attr': 'real', 'coeff': 33},
  {'attr': 'real', 'coeff': 34},
  {'attr': 'real', 'coeff': 35},
  {'attr': 'real', 'coeff': 36},
  {'attr': 'real', 'coeff': 37},
  {'attr': 'real', 'coeff': 38},
  {'attr': 'real', 'coeff': 39},
  {'attr': 'real', 'coeff': 40},
  {'attr': 'real', 'coeff': 41},
  {'attr': 'real', 'coeff': 42},
  {'attr': 'real', 'coeff': 43},
  {'attr': 'real', 'coeff': 44},
  {'attr': 'real', 'coeff': 45},
  {'attr': 'real', 'coeff': 46},
  {'attr': 'real', 'coeff': 47},
  {'attr': 'real', 'coeff': 48},
  {'attr': 'real', 'coeff': 49},
  {'attr': 'real', 'coeff': 50},
  {'attr': 'real', 'coeff': 51},
  {'attr': 'real', 'coeff': 52},
  {'attr': 'real', 'coeff': 53},
  {'attr': 'real', 'coeff': 54},
  {'attr': 'real', 'coeff': 55},
  {'attr': 'real', 'coeff': 56},
  {'attr': 'real', 'coeff': 57},
  {'attr': 'real', 'coeff': 58},
  {'attr': 'real', 'coeff': 59},
  {'attr': 'real', 'coeff': 60},
  {'attr': 'real', 'coeff': 61},
  {'attr': 'real', 'coeff': 62},
  {'attr': 'real', 'coeff': 63},
  {'attr': 'real', 'coeff': 64},
  {'attr': 'real', 'coeff': 65},
  {'attr': 'real', 'coeff': 66},
  {'attr': 'real', 'coeff': 67},
  {'attr': 'real', 'coeff': 68},
  {'attr': 'real', 'coeff': 69},
  {'attr': 'real', 'coeff': 70},
  {'attr': 'real', 'coeff': 71},
  {'attr': 'real', 'coeff': 72},
  {'attr': 'real', 'coeff': 73},
  {'attr': 'real', 'coeff': 74},
  {'attr': 'real', 'coeff': 75},
  {'attr': 'real', 'coeff': 76},
  {'attr': 'real', 'coeff': 77},
  {'attr': 'real', 'coeff': 78},
  {'attr': 'real', 'coeff': 79},
  {'attr': 'real', 'coeff': 80},
  {'attr': 'real', 'coeff': 81},
  {'attr': 'real', 'coeff': 82},
  {'attr': 'real', 'coeff': 83},
  {'attr': 'real', 'coeff': 84},
  {'attr': 'real', 'coeff': 85},
  {'attr': 'real', 'coeff': 86},
  {'attr': 'real', 'coeff': 87},
  {'attr': 'real', 'coeff': 88},
  {'attr': 'real', 'coeff': 89},
  {'attr': 'real', 'coeff': 90},
  {'attr': 'real', 'coeff': 91},
  {'attr': 'real', 'coeff': 92},
  {'attr': 'real', 'coeff': 93},
  {'attr': 'real', 'coeff': 94},
  {'attr': 'real', 'coeff': 95},
  {'attr': 'real', 'coeff': 96},
  {'attr': 'real', 'coeff': 97},
  {'attr': 'real', 'coeff': 98},
  {'attr': 'real', 'coeff': 99},
  {'attr': 'imag', 'coeff': 0},
  {'attr': 'imag', 'coeff': 1},
  {'attr': 'imag', 'coeff': 2},
  {'attr': 'imag', 'coeff': 3},
  {'attr': 'imag', 'coeff': 4},
  {'attr': 'imag', 'coeff': 5},
  {'attr': 'imag', 'coeff': 6},
  {'attr': 'imag', 'coeff': 7},
  {'attr': 'imag', 'coeff': 8},
  {'attr': 'imag', 'coeff': 9},
  {'attr': 'imag', 'coeff': 10},
  {'attr': 'imag', 'coeff': 11},
  {'attr': 'imag', 'coeff': 12},
  {'attr': 'imag', 'coeff': 13},
  {'attr': 'imag', 'coeff': 14},
  {'attr': 'imag', 'coeff': 15},
  {'attr': 'imag', 'coeff': 16},
  {'attr': 'imag', 'coeff': 17},
  {'attr': 'imag', 'coeff': 18},
  {'attr': 'imag', 'coeff': 19},
  {'attr': 'imag', 'coeff': 20},
  {'attr': 'imag', 'coeff': 21},
  {'attr': 'imag', 'coeff': 22},
  {'attr': 'imag', 'coeff': 23},
  {'attr': 'imag', 'coeff': 24},
  {'attr': 'imag', 'coeff': 25},
  {'attr': 'imag', 'coeff': 26},
  {'attr': 'imag', 'coeff': 27},
  {'attr': 'imag', 'coeff': 28},
  {'attr': 'imag', 'coeff': 29},
  {'attr': 'imag', 'coeff': 30},
  {'attr': 'imag', 'coeff': 31},
  {'attr': 'imag', 'coeff': 32},
  {'attr': 'imag', 'coeff': 33},
  {'attr': 'imag', 'coeff': 34},
  {'attr': 'imag', 'coeff': 35},
  {'attr': 'imag', 'coeff': 36},
  {'attr': 'imag', 'coeff': 37},
  {'attr': 'imag', 'coeff': 38},
  {'attr': 'imag', 'coeff': 39},
  {'attr': 'imag', 'coeff': 40},
  {'attr': 'imag', 'coeff': 41},
  {'attr': 'imag', 'coeff': 42},
  {'attr': 'imag', 'coeff': 43},
  {'attr': 'imag', 'coeff': 44},
  {'attr': 'imag', 'coeff': 45},
  {'attr': 'imag', 'coeff': 46},
  {'attr': 'imag', 'coeff': 47},
  {'attr': 'imag', 'coeff': 48},
  {'attr': 'imag', 'coeff': 49},
  {'attr': 'imag', 'coeff': 50},
  {'attr': 'imag', 'coeff': 51},
  {'attr': 'imag', 'coeff': 52},
  {'attr': 'imag', 'coeff': 53},
  {'attr': 'imag', 'coeff': 54},
  {'attr': 'imag', 'coeff': 55},
  {'attr': 'imag', 'coeff': 56},
  {'attr': 'imag', 'coeff': 57},
  {'attr': 'imag', 'coeff': 58},
  {'attr': 'imag', 'coeff': 59},
  {'attr': 'imag', 'coeff': 60},
  {'attr': 'imag', 'coeff': 61},
  {'attr': 'imag', 'coeff': 62},
  {'attr': 'imag', 'coeff': 63},
  {'attr': 'imag', 'coeff': 64},
  {'attr': 'imag', 'coeff': 65},
  {'attr': 'imag', 'coeff': 66},
  {'attr': 'imag', 'coeff': 67},
  {'attr': 'imag', 'coeff': 68},
  {'attr': 'imag', 'coeff': 69},
  {'attr': 'imag', 'coeff': 70},
  {'attr': 'imag', 'coeff': 71},
  {'attr': 'imag', 'coeff': 72},
  {'attr': 'imag', 'coeff': 73},
  {'attr': 'imag', 'coeff': 74},
  {'attr': 'imag', 'coeff': 75},
  {'attr': 'imag', 'coeff': 76},
  {'attr': 'imag', 'coeff': 77},
  {'attr': 'imag', 'coeff': 78},
  {'attr': 'imag', 'coeff': 79},
  {'attr': 'imag', 'coeff': 80},
  {'attr': 'imag', 'coeff': 81},
  {'attr': 'imag', 'coeff': 82},
  {'attr': 'imag', 'coeff': 83},
  {'attr': 'imag', 'coeff': 84},
  {'attr': 'imag', 'coeff': 85},
  {'attr': 'imag', 'coeff': 86},
  {'attr': 'imag', 'coeff': 87},
  {'attr': 'imag', 'coeff': 88},
  {'attr': 'imag', 'coeff': 89},
  {'attr': 'imag', 'coeff': 90},
  {'attr': 'imag', 'coeff': 91},
  {'attr': 'imag', 'coeff': 92},
  {'attr': 'imag', 'coeff': 93},
  {'attr': 'imag', 'coeff': 94},
  {'attr': 'imag', 'coeff': 95},
  {'attr': 'imag', 'coeff': 96},
  {'attr': 'imag', 'coeff': 97},
  {'attr': 'imag', 'coeff': 98},
  {'attr': 'imag', 'coeff': 99}],
 'first_location_of_maximum': None,
 'first_location_of_minimum': None,
 'friedrich_coefficients': [{'coeff': 0, 'm': 3, 'r': 30},
  {'coeff': 1, 'm': 3, 'r': 30},
  {'coeff': 2, 'm': 3, 'r': 30},
  {'coeff': 3, 'm': 3, 'r': 30}],
 'has_duplicate': None,
 'has_duplicate_max': None,
 'has_duplicate_min': None,
 'index_mass_quantile': [{'q': 0.1},
  {'q': 0.2},
  {'q': 0.3},
  {'q': 0.4},
  {'q': 0.6},
  {'q': 0.7},
  {'q': 0.8},
  {'q': 0.9}],
 'kurtosis': None,
 'large_standard_deviation': [{'r': 0.05},
  {'r': 0.1},
  {'r': 0.15000000000000002},
  {'r': 0.2},
  {'r': 0.25},
  {'r': 0.30000000000000004},
  {'r': 0.35000000000000003},
  {'r': 0.4},
  {'r': 0.45},
  {'r': 0.5},
  {'r': 0.55},
  {'r': 0.6000000000000001},
  {'r': 0.65},
  {'r': 0.7000000000000001},
  {'r': 0.75},
  {'r': 0.8},
  {'r': 0.8500000000000001},
  {'r': 0.9},
  {'r': 0.9500000000000001}],
 'last_location_of_maximum': None,
 'last_location_of_minimum': None,
 'length': None,
 'linear_trend': [{'attr': 'pvalue'},
  {'attr': 'rvalue'},
  {'attr': 'intercept'},
  {'attr': 'slope'},
  {'attr': 'stderr'}],
 'longest_strike_above_mean': None,
 'longest_strike_below_mean': None,
 'max_langevin_fixed_point': [{'m': 3, 'r': 30}],
 'maximum': None,
 'mean': None,
 'mean_abs_change': None,
 'mean_change': None,
 'mean_second_derivate_central': None,
 'median': None,
 'minimum': None,
 'number_crossing_m': [{'m': 0}, {'m': -1}, {'m': 1}],
 'number_cwt_peaks': [{'n': 1}, {'n': 5}],
 'number_peaks': [{'n': 1}, {'n': 3}, {'n': 5}, {'n': 10}, {'n': 50}],
 'percentage_of_reoccurring_datapoints_to_all_datapoints': None,
 'percentage_of_reoccurring_values_to_all_values': None,
 'quantile': [{'q': 0.1},
  {'q': 0.2},
  {'q': 0.3},
  {'q': 0.4},
  {'q': 0.6},
  {'q': 0.7},
  {'q': 0.8},
  {'q': 0.9}],
 'range_count': [{'max': 1, 'min': -1}],
 'ratio_value_number_to_time_series_length': None,
 'sample_entropy': None,
 'skewness': None,
 'spkt_welch_density': [{'coeff': 2}, {'coeff': 5}, {'coeff': 8}],
 'standard_deviation': None,
 'sum_of_reoccurring_data_points': None,
 'sum_of_reoccurring_values': None,
 'sum_values': None,
 'symmetry_looking': [{'r': 0.0},
  {'r': 0.05},
  {'r': 0.1},
  {'r': 0.15000000000000002},
  {'r': 0.2},
  {'r': 0.25},
  {'r': 0.30000000000000004},
  {'r': 0.35000000000000003},
  {'r': 0.4},
  {'r': 0.45},
  {'r': 0.5},
  {'r': 0.55},
  {'r': 0.6000000000000001},
  {'r': 0.65},
  {'r': 0.7000000000000001},
  {'r': 0.75},
  {'r': 0.8},
  {'r': 0.8500000000000001},
  {'r': 0.9},
  {'r': 0.9500000000000001}],
 'time_reversal_asymmetry_statistic': [{'lag': 1}, {'lag': 2}, {'lag': 3}],
 'value_count': [{'value': 0},
  {'value': 1},
  {'value': nan},
  {'value': inf},
  {'value': -inf}],
 'variance': None,
 'variance_larger_than_standard_deviation': None}