-- MySQL Script generated by MySQL Workbench
-- Sat Jan 28 09:53:35 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=`TRADITIONAL,ALLOW_INVALID_DATES`;

-- -----------------------------------------------------
-- Schema sharecast
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sharecast
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sharecast` DEFAULT CHARACTER SET utf8 ;
USE `sharecast` ;

-- -----------------------------------------------------
-- Table `sharecast`.`inflation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharecast`.`inflation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `effective_date` DATETIME NULL,
  `value` DECIMAL(6,4) NULL,
  `year_month` VARCHAR(6) NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `date_index` (`effective_date` ASC),
  INDEX `year_month` (`year_month` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharecast`.`gdp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharecast`.`gdp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `effective_date` DATETIME NULL,
  `value` DECIMAL(15,0) NULL,
  `year_month` VARCHAR(6) NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `date_index` (`effective_date` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharecast`.`commodity_prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharecast`.`commodity_prices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `effective_date` DATETIME NULL,
  `commodity_type` VARCHAR(45) NULL,
  `value` DECIMAL(12,4) NULL,
  `year_month` VARCHAR(6) NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `date_index` (`effective_date` ASC),
  INDEX `year_month` (`year_month` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharecast`.`interest_rates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharecast`.`interest_rates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `effective_date` DATETIME NULL,
  `value` DECIMAL(6,4) NULL,
  `year_month` VARCHAR(6) NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `date_index` (`effective_date` ASC),
  INDEX `year_month` (`year_month` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharecast`.`share_indices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharecast`.`share_indices` (
  `index_symbol` VARCHAR(10) NOT NULL,
  `index_name` VARCHAR(45) NOT NULL,
  `index_symbol_yahoo` VARCHAR(45) NOT NULL,
  `index_symbol_google` VARCHAR(45) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`index_symbol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharecast`.`share_index_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharecast`.`share_index_values` (
  `index_value_id` INT NOT NULL AUTO_INCREMENT,
  `index_symbol` VARCHAR(10) NOT NULL,
  `effective_date` DATETIME NOT NULL,
  `open` DECIMAL(45,18) NULL,
  `high` DECIMAL(45,18) NULL,
  `low` DECIMAL(45,18) NULL,
  `close` DECIMAL(45,18) NULL,
  `adjusted_close` DECIMAL(45,18) NULL,
  `volume` INT(11) NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`index_value_id`),
  INDEX `index_id` (`index_symbol` ASC),
  INDEX `index_date` (`effective_date` ASC),
  CONSTRAINT `index_id`
    FOREIGN KEY (`index_symbol`)
    REFERENCES `sharecast`.`share_indices` (`index_symbol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharecast`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharecast`.`companies` (
  `company_symbol` VARCHAR(10) NOT NULL,
  `company_name` VARCHAR(100) NOT NULL,
  `company_symbol_yahoo` VARCHAR(20) NOT NULL,
  `company_symbol_google` VARCHAR(20) NOT NULL,
  `watching_company` TINYINT(1) NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`company_symbol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharecast`.`company_metrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharecast`.`company_metrics` (
  `company_metrics_id` INT NOT NULL AUTO_INCREMENT,
  `company_symbol` VARCHAR(10) NOT NULL,
  `metrics_date` DATE NULL,
  `year_month` VARCHAR(6) NULL,
  `eps` DECIMAL(45,18) NULL,
  `quotelast` DECIMAL(45,18) NULL,
  `price200dayaverage` DECIMAL(45,18) NULL,
  `price52weekpercchange` DECIMAL(45,18) NULL,
  `pricetobook` DECIMAL(45,18) NULL,
  `marketcap` DECIMAL(45,18) NULL,
  `pe` DECIMAL(45,18) NULL,
  `dividendrecentquarter` DECIMAL(45,18) NULL,
  `dividendnextquarter` DECIMAL(45,18) NULL,
  `dpsrecentyear` DECIMAL(45,18) NULL,
  `iad` DECIMAL(45,18) NULL,
  `dividendpershare` DECIMAL(45,18) NULL,
  `dividendyield` DECIMAL(45,18) NULL,
  `dividend` DECIMAL(45,18) NULL,
  `bookvaluepershareyear` DECIMAL(45,18) NULL,
  `cashpershareyear` DECIMAL(45,18) NULL,
  `currentratioyear` DECIMAL(45,18) NULL,
  `ltdebttoassetsyear` DECIMAL(45,18) NULL,
  `ltdebttoassetsquarter` DECIMAL(45,18) NULL,
  `totaldebttoassetsyear` DECIMAL(45,18) NULL,
  `totaldebttoassetsquarter` DECIMAL(45,18) NULL,
  `ltdebttoequityyear` DECIMAL(45,18) NULL,
  `ltdebttoequityquarter` DECIMAL(45,18) NULL,
  `totaldebttoequityyear` DECIMAL(45,18) NULL,
  `totaldebttoequityquarter` DECIMAL(45,18) NULL,
  `aintcov` DECIMAL(45,18) NULL,
  `returnoninvestmentttm` DECIMAL(45,18) NULL,
  `returnoninvestment5years` DECIMAL(45,18) NULL,
  `returnoninvestmentyear` DECIMAL(45,18) NULL,
  `returnonassetsttm` DECIMAL(45,18) NULL,
  `returnonassets5years` DECIMAL(45,18) NULL,
  `returnonassetsyear` DECIMAL(45,18) NULL,
  `returnonequityttm` DECIMAL(45,18) NULL,
  `returnonequity5years` DECIMAL(45,18) NULL,
  `returnonequityyear` DECIMAL(45,18) NULL,
  `beta` DECIMAL(45,18) NULL,
  `float` DECIMAL(45,18) NULL,
  `institutionalpercentheld` DECIMAL(45,18) NULL,
  `grossmargin` DECIMAL(45,18) NULL,
  `ebitdmargin` DECIMAL(45,18) NULL,
  `operatingmargin` DECIMAL(45,18) NULL,
  `netprofitmarginpercent` DECIMAL(45,18) NULL,
  `netincomegrowthrate5years` DECIMAL(45,18) NULL,
  `revenuegrowthrate5years` DECIMAL(45,18) NULL,
  `revenuegrowthrate10years` DECIMAL(45,18) NULL,
  `epsgrowthrate5years` DECIMAL(45,18) NULL,
  `epsgrowthrate10years` DECIMAL(45,18) NULL,
  `volume` DECIMAL(45,18) NULL,
  `averagevolume` DECIMAL(45,18) NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`company_metrics_id`),
  INDEX `metrics_date` (`metrics_date` ASC),
  INDEX `year_month` (`year_month` ASC))
ENGINE = InnoDB;

CREATE USER `sharecast-user`;

GRANT SELECT, INSERT, TRIGGER ON TABLE `sharecast`.* TO `sharecast-user`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
